"""add column to schedule for count message for client

Revision ID: 334c2959b6d9
Revises: c8a457832864
Create Date: 2019-11-25 15:11:57.738726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334c2959b6d9'
down_revision = 'c8a457832864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_of_day', sa.Column('info_message_for_client', sa.Integer(), nullable=True))
    op.add_column('schedule_of_day', sa.Column('remind_message_for_client', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_of_day', 'remind_message_for_client')
    op.drop_column('schedule_of_day', 'info_message_for_client')
    # ### end Alembic commands ###
