"""add to_show news

Revision ID: 44e7a0c7f29b
Revises: a89bef42aacb
Create Date: 2019-11-22 11:39:26.016999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e7a0c7f29b'
down_revision = 'a89bef42aacb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('show', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'show')
    # ### end Alembic commands ###
