"""add field to user - reg from master2

Revision ID: 4aa431a31f53
Revises: 87cc12cf258f
Create Date: 2019-11-14 14:22:52.467803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa431a31f53'
down_revision = '87cc12cf258f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_from_master', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_from_master')
    # ### end Alembic commands ###
