"""add second email

Revision ID: 6df34e38e11f
Revises: e25e1e1ef1c6
Create Date: 2019-09-01 12:16:56.210237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df34e38e11f'
down_revision = 'e25e1e1ef1c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email2', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_email2'), 'user', ['email2'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email2'), table_name='user')
    op.drop_column('user', 'email2')
    # ### end Alembic commands ###
