"""add field to user - reg from master

Revision ID: 87cc12cf258f
Revises: 674f8ba0f64b
Create Date: 2019-11-14 14:18:54.552823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87cc12cf258f'
down_revision = '674f8ba0f64b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_phones', sa.Column('user_from_master', sa.Integer()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_phones', 'user_from_master')
    # ### end Alembic commands ###
