"""add type works

Revision ID: 96d6be4c6e72
Revises: c2a21bc714ce
Create Date: 2019-11-30 14:12:14.023768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d6be4c6e72'
down_revision = 'c2a21bc714ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('price_list', sa.Column('work_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'price_list', 'work_type', ['work_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price_list', type_='foreignkey')
    op.drop_column('price_list', 'work_type_id')
    op.drop_table('work_type')
    # ### end Alembic commands ###
