"""Add type connection to client

Revision ID: a9fd564766c7
Revises: d60b409f930a
Create Date: 2019-10-29 10:52:54.473411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9fd564766c7'
down_revision = 'd60b409f930a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_of_day', sa.Column('connection_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_of_day', 'connection_type')
    # ### end Alembic commands ###
