"""add_table_internet_acc_connection

Revision ID: b4abe9eebcea
Revises: a9fd564766c7
Create Date: 2019-11-11 13:47:31.765413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4abe9eebcea'
down_revision = 'a9fd564766c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_internet_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adress_accaunt', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'adress_accaunt')
    )
    op.create_index(op.f('ix_user_internet_account_adress_accaunt'), 'user_internet_account', ['adress_accaunt'], unique=True)
    op.add_column('schedule_of_day', sa.Column('mail_of_client', sa.String(), nullable=True))
    op.add_column('schedule_of_day', sa.Column('phone_of_client', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_of_day', 'phone_of_client')
    op.drop_column('schedule_of_day', 'mail_of_client')
    op.drop_index(op.f('ix_user_internet_account_adress_accaunt'), table_name='user_internet_account')
    op.drop_table('user_internet_account')
    # ### end Alembic commands ###
