"""add master profel to user

Revision ID: c8862c8110c1
Revises: 2f1f9fce55e0
Create Date: 2019-12-02 15:01:22.821644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8862c8110c1'
down_revision = '2f1f9fce55e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nail_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('work_phone', sa.Integer(), nullable=True),
    sa.Column('work_instagram', sa.String(length=250), nullable=True),
    sa.Column('work_vk', sa.String(length=250), nullable=True),
    sa.Column('work_telegram', sa.String(length=250), nullable=True),
    sa.Column('work_mail', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nail_master')
    # ### end Alembic commands ###
