"""first_migration

Revision ID: d60b409f930a
Revises: 
Create Date: 2019-10-09 11:40:31.034362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60b409f930a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('date_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_date', sa.DateTime(), nullable=True),
    sa.Column('day_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('my_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_site', sa.Integer(), nullable=True),
    sa.Column('published', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('show', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('main_picture_url', sa.String(), nullable=True),
    sa.Column('published', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('russian_mobil_operator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Operator', sa.String(), nullable=False),
    sa.Column('Count', sa.String(), nullable=False),
    sa.Column('Count_parse', sa.Integer(), nullable=True),
    sa.Column('Note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Code', sa.Integer(), nullable=False),
    sa.Column('ZoneText', sa.String(), nullable=True),
    sa.Column('Count', sa.String(), nullable=False),
    sa.Column('Count_parse', sa.Integer(), nullable=True),
    sa.Column('RussianMobilOperator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['RussianMobilOperator_id'], ['russian_mobil_operator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments_to_my_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_site', sa.Integer(), nullable=True),
    sa.Column('media', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('published', sa.DateTime(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('show', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('my_work_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['my_work_id'], ['my_work.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_to_my_works_my_work_id'), 'comments_to_my_works', ['my_work_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('email_confirmed', sa.Integer(), nullable=True),
    sa.Column('expire_date_request_confirm_password', sa.DateTime(), nullable=True),
    sa.Column('expire_date_request_bufer_mail', sa.DateTime(), nullable=True),
    sa.Column('bufer_email', sa.String(length=120), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('trying_to_enter_new_phone', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('connection_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['connection_type_id'], ['connection_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('comments_to_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_to_news_news_id'), 'comments_to_news', ['news_id'], unique=False)
    op.create_index(op.f('ix_comments_to_news_user_id'), 'comments_to_news', ['user_id'], unique=False)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('schedule_of_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('begin_time_of_day', sa.DateTime(), nullable=True),
    sa.Column('end_time_of_day', sa.DateTime(), nullable=True),
    sa.Column('work_type', sa.String(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('name_of_client', sa.String(), nullable=True),
    sa.Column('adress_of_client', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('client_come_in', sa.Integer(), nullable=True),
    sa.Column('is_empty', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['date_table_id'], ['date_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('phone_hash_code', sa.String(length=128), nullable=True),
    sa.Column('phone_checked', sa.Integer(), nullable=False),
    sa.Column('expire_date_hash', sa.DateTime(), nullable=True),
    sa.Column('black_list', sa.Integer(), nullable=False),
    sa.Column('trying_to_enter_confirm_code', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_phones')
    op.drop_table('schedule_of_day')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('followers')
    op.drop_index(op.f('ix_comments_to_news_user_id'), table_name='comments_to_news')
    op.drop_index(op.f('ix_comments_to_news_news_id'), table_name='comments_to_news')
    op.drop_table('comments_to_news')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_comments_to_my_works_my_work_id'), table_name='comments_to_my_works')
    op.drop_table('comments_to_my_works')
    op.drop_table('code_zone')
    op.drop_table('russian_mobil_operator')
    op.drop_table('news')
    op.drop_table('my_work')
    op.drop_table('date_table')
    op.drop_table('connection_type')
    # ### end Alembic commands ###
