"""add to_show news_comment

Revision ID: ea8ca5d09dec
Revises: 44e7a0c7f29b
Create Date: 2019-11-22 17:13:30.512263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea8ca5d09dec'
down_revision = '44e7a0c7f29b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments_to_news', sa.Column('show', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments_to_news', 'show')
    # ### end Alembic commands ###
